### ISSUE TITLE
TYPO: passward => password

### ISSUE THREAD

**Issue by ggzengel** [Wiznet/WIZnet-S2E-Tool-GUI#1]
https://github.com/Wiznet/WIZnet-S2E-Tool-GUI/blob/1ffef05c418e50a8270fa9c2a6f3c04ff8e04fcf/gui/wizconfig_gui.ui#L3661

https://github.com/Wiznet/WIZnet-S2E-Tool-GUI/blob/1ffef05c418e50a8270fa9c2a6f3c04ff8e04fcf/gui/wizconfig_gui.ui#L3738

**Comment by renakim** [comment]
Thank you.
This will be update on next version.
