### ISSUE TITLE
Search Multiple Devices via UDP broadcast 

### ISSUE THREAD

**Issue by jtronics** [Wiznet/WIZnet-S2E-Tool-GUI#18]
Hello,
I have 3 Wiz750SR and 1 computer on my network. The Devices are connected via a switch.
I'm trying to search multiple devices via method UDP broadcast. But Not device is found. All settings are default.
If ther is only 1 Wiz750SR connected, it's found.
There is no firewall or virus software aktiv.
http://wizwiki.net/wiki/doku.php/products:wiz750sr:download:start#wiznet_s2e_configuration_tool

What's the problem?

Best regards

**Comment by WIZplatform** [comment]
Hi~
S2E Configuration tool can search the multiple devices.
I think 3 Wiz750sr use same IP address.
Could you please change separate IP address(static or DHCP) of devices and try again?

**Comment by irinakim12** [comment]
Hi~
S2E Configuration tool can search the multiple devices.
I think 3 Wiz750sr use same IP address.
Could you please change separate IP address(static or DHCP) of devices and try again?

**Comment by renakim** [comment]
Hello, 
If the devices are on the same network, they must be searched.
To check the problem, I need the following information.

1. Device configuration information
: Configuration tool screen capture

2. Network packet files, using Wireshark

Please check these.

**Comment by renakim** [comment]
Hello, @jtronics.
Did you solve the problem?
