### ISSUE TITLE
Feature Request: Implement TCP Unicast Mode

### ISSUE THREAD

**Issue by ggzengel** [Wiznet/WIZnet-S2E-Tool-GUI#2]
My modules are always in an other subnet.
So please add unicast mode like in old config tool.

**Comment by renakim** [comment]
Thank you for your interest. 
TCP unicast mode will be updated soon.

**Comment by renakim** [comment]
Hi, @ggzengel  
TCP unicast mode is available in 0.5.1 beta version or later.
Thank you.
