### ISSUE TITLE
Issue when press "Apply Setting" with "wizconfig-V1.3.0" and WIZ750SR v.1.3.3

### ISSUE THREAD

**Issue by andbarb** [Wiznet/WIZnet-S2E-Tool-GUI#23]
When press "Apply Setting" displayed
![image](https://user-images.githubusercontent.com/80947435/111758948-61623080-889d-11eb-9dbe-f9573239994f.png)

After press "Yes" displayed
![image](https://user-images.githubusercontent.com/80947435/111759119-8fe00b80-889d-11eb-89c7-1cb3f19ac540.png)

With WIZ750SR-1xx module this error don't appears.
Thanks

**Comment by renakim** [comment]
Hi @andbarb,
Thank you for the leave issue.

According to the message in the pop-up, it appears to be a problem caused by the device settings.
but in my environment, I can't find that message. (WIZ750SR V1.3.3 & wizconfig V1.3.0)

So could you capture some packets using Wireshark while using the configuration tool?
By analyzing the packet, can determine the cause of the problem.

**Comment by andbarb** [comment]
Hi @renakim,
Thank for response.

The previous shipment lot did not give this problem.
However the wiz750sr seems to work fine, and I am not allowed to take the time to investigate the problem, is there another solutions?

**Comment by renakim** [comment]
Hi @andbarb,
Ok, then could you capture the entire screen of the Configuration Tool?
According to the error message, it seems like a problem with the tool caused by some setting value of WIZ750SR.

**Comment by andbarb** [comment]
Hi @renakim,
thank you very much.
![ConfWizNet](https://user-images.githubusercontent.com/80947435/112112192-82849300-8bb5-11eb-9818-4292c205b259.JPG)

You see, the problem also exists with the previous version of Wizconfig (1.1.0)
I confirm, it is a problem with the lot received in March 2021, the penultimate shipment received in February did not present the problem (as well as previous shipments).
I tried on several PCs but the situation does not change.

**Comment by renakim** [comment]
Do you mean that the operation is different between the previously received device and the newly?
Is the firmware version is different?
If that, the operation could be different, but if not, it is not understood.

I'm testing with WIZ750SR-v1.3.3, but I haven't found that problem yet.

Can you check the data number of the device? (There is a round sticker on the side of the module like below)
![image](https://user-images.githubusercontent.com/29771876/112400764-5f401c00-8d4c-11eb-8666-879f0247c81c.png)

**Comment by andbarb** [comment]
> Do you mean that the operation is different between the previously received device and the newly? **_Yes_**
> Is the firmware version is different? **_I don't know_**
> Can you check the data number of the device? **_Yes_**, this is the newly, with problem
![IMG_20210325_084127_web](https://user-images.githubusercontent.com/80947435/112439184-18045c00-8d49-11eb-8836-4b96534b9569.jpg)


This is the previously, without the problem
![IMG_20210325_084348_web](https://user-images.githubusercontent.com/80947435/112439226-26eb0e80-8d49-11eb-8ac5-1de76aac471d.jpg)

**Comment by renakim** [comment]
Thank you for the information.

In the pictures, the firmware version of the two devices same. (v1.3.3)
However, it looks like the name of the second device is wrong. (device H/W: WIZ750SR / type in tool: WIZ750SR-1xx)
For proper operation, it is recommended to perform a factory reset on the device first, and if the problem is not resolved, perform a full F/W update.

For the config tool pop-up message, I'll notify you after checking more.

**Comment by andbarb** [comment]
Hi @renakim,
I don't understand.
The problem is with the new device received (WIZ750SR, 2104, the first in my photo) and not with the previously device received (WIZ750SR-1xx, 2014).
I have not WIZ750SR-1xx, I have sold them all and they are working fine (about 60-100 pcs), if you tell me needing fw reset should i worry?

**Comment by renakim** [comment]
Factory reset is a recommendation, and if the devices sold are working well, don't need to do a factory reset.
Looking at the second picture, the name(type) displayed in the Config tool is WIZ750SR-1xx, but the actual device shown is WIZ750SR, which does not match the name.
The device displayed as WIZ750SR-1xx in the tool is WIZ750SR-100/105/110 and has a different shape from WIZ750SR.
Please note this.

Can you save and share your settings to check tool issues?
You can save the settings using the 'Save config' button. (.cfg)
![image](https://user-images.githubusercontent.com/29771876/112771590-7db55880-9067-11eb-8c76-2f9388a7e6ea.png)
(My email address: rena@wiznet.io)

**Comment by renakim** [comment]
Hi @andbarb,
I updated the code and upload an executable file to release (V1.3.1).
Thank you.
